### ISSUE TITLE
Entire screen blanks out when 7 or more items are in the list on Microsoft Edge

### ISSUE THREAD

**Issue by leelandclay** [dizco/react-scrollable-feed#20]
**Describe the bug**
When there are more than just a few entries within the ScrollableFeed, Microsoft Edge will blank.

**To Reproduce**
1. Go to the Live Demo screen on Microsoft Edge (https://dizco.github.io/react-scrollable-feed/)
2. Click Add Item until screen blanks (for me it happens consistently at 7)

**Expected behavior**
Screen to not blank and the items in the ScrollableFeed to be displayed properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Edge
 - Version Microsoft Edge 44.18362.449.0

This is the error displayed within the console:

```
[object Error]: {description: "Object doesn't support property or method 'scrollBy'", message: "Object doesn't support property or method 'scrollBy'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'scrollBy' at t.defaultProps.animateScroll (https://dizco.github.io/react-scrollable-feed/static/js/main.d2e505ac.chunk.js:1:2559) at t.prototype.scrollParentToChild (https://dizco.github.io/react-scrollable-feed/static/js/main.d2e505ac.chunk.js:1:2098) at t.prototype.componentDidUpdate (https://dizco.github.io/react-scrollable-feed/static/js/main.d2e505ac.chunk.js:1:1514) at Mi (https://dizco.github.io/react-scrollable-feed/static/js/1.e63eb374.chunk.js:1:99275) at Ri (https://dizco.github.io/react-scrollable-feed/static/js/1.e63eb374.chunk.js:1:94905) at Oi (https://dizco.github.io/react-scrollable-feed/static/js/1.e63eb374.chunk.js:1:94277) at ji (https://dizco.github.io/react-scrollable-feed/static/js/1.e63eb374.chunk.js:1:100475) at Sn (https://dizco.github.io/react-scrollable-feed/static/js/1.e63eb374.chunk.js:1:39902)"}
```

**Comment by dizco** [comment]
Please try v1.1.1 :)
